version: "3"
services:
  huecontrol:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./src/assets/config.json:/usr/share/nginx/html/assets/config.json:ro"
      # runtime-based CORS proxy Nginx configuration:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw"
